/**
 * AUTO-GENERATED FILE @ Tue, 21 Dec 2021 12:00:34 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.0.0.12
 * $ schemats generate postgres://username:password@localhost:5432/alpacasalon -s public
 *
 */

export interface user_x_group {
  user_id: string
  group_id: number
  creation_time: Date
}

export interface poll_comment {
  id: number
  creation_time?: Date | null
  modification_time?: Date | null
  contents?: string | null
  image_urls?: string[] | null
  poll_comment_id?: number | null
  poll_id?: number | null
  user_id?: string | null
}

export interface poll_selection_x_user {
  poll_selection_id: number
  user_id: string
  creation_time: Date
}

export interface poll_selection {
  id: number
  creation_time: Date
  contents: string
  count?: number | null
  poll_id?: number | null
}

export interface comment {
  id: number
  creation_time?: Date | null
  modification_time?: Date | null
  contents?: string | null
  image_urls?: string[] | null
  comment_id?: number | null
  post_id?: number | null
  user_id?: string | null
}

export interface user {
  id: string
  creation_time: Date
  modification_time: Date
  email?: string | null
  nickname?: string | null
  phone_number?: string | null
  birthyear?: string | null
  birthday?: string | null
  gender?: number | null
  bio?: string | null
  image_url?: string | null
  kakao_oauth?: string | null
  validation_time: Date
}

export interface post {
  id: number
  creation_time?: Date | null
  modification_time?: Date | null
  title: string
  contents: string
  image_urls?: string[] | null
  user_id?: string | null
  group_id?: number | null
}

export interface user_x_liked_poll_comment {
  user_id: string
  poll_comment_id: number
  creation_time: Date
}

export interface user_x_liked_comment {
  user_id: string
  comment_id: number
  creation_time: Date
}

export interface poll {
  id: number
  creation_time: Date
  closing_time?: Date | null
  title: string
  status: number
  contents?: string | null
}

export interface group {
  id: number
  creation_time?: Date | null
  modification_time?: Date | null
  name: string
  description?: string | null
  image_url?: string | null
}

export interface notification {
  id: number
  creation_time: Date
  type: number
  contents: string
  receiver_id: string
  sender_id?: string | null
}

export interface Tables {
  user_x_group: user_x_group
  poll_comment: poll_comment
  poll_selection_x_user: poll_selection_x_user
  poll_selection: poll_selection
  comment: comment
  user: user
  post: post
  user_x_liked_poll_comment: user_x_liked_poll_comment
  user_x_liked_comment: user_x_liked_comment
  poll: poll
  group: group
  notification: notification
}
